name: 'Configure thiscovery test environment'
description: 'Configures GitHub Action pipelines to use as test environment the AWS account of the developer who initiated the pipeline (actor)'
inputs:
  actor:
    description: 'GitHub username of thiscovery developer'
    required: true
runs:
  using: "composite"
  steps:
    # Configure target test account based on actor
    - if: ${{ inputs.actor == 'afs25' }}
    name: Sets env vars for afs25
    run: |
      echo "AWS_TEST_ACCOUNT=${{ secrets.AFS25_AWS_ACCOUNT }}" >> $GITHUB_ENV
      echo "AWS_TEST_ENV=test-afs25" >> $GITHUB_ENV
  
  - if: ${{ inputs.actor == 'sophiemachin' }}
    name: Sets env vars for sem86
    run: |
      echo "AWS_TEST_ACCOUNT=${{ secrets.SEM86_AWS_ACCOUNT }}" >> $GITHUB_ENV
      echo "AWS_TEST_ENV=test-sem86" >> $GITHUB_ENV
  
  - if: ${{ inputs.actor == 'this-andy' }}
    name: Sets env vars for amp205
    run: |
      echo "AWS_TEST_ACCOUNT=${{ secrets.AMP205_AWS_ACCOUNT }}" >> $GITHUB_ENV
      echo "AWS_TEST_ENV=test-amp205" >> $GITHUB_ENV
  
  - name: Set additional env variables
    run: |
      echo "SECRETS_NAMESPACE=/${AWS_TEST_ENV}/" >> $GITHUB_ENV
      echo "UNIT_TEST_NAMESPACE=/${AWS_TEST_ENV}/" >> $GITHUB_ENV
      echo "TEST_ON_AWS=True" >> $GITHUB_ENV
      echo "TESTING_ACCOUNT_DEPLOYMENT_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-devops-${AWS_TEST_ENV}-${AWS_REGION}-PipelineExec" >> $GITHUB_ENV
      echo "TESTING_ACCOUNT_TEST_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-dev-setup-${AWS_TEST_ENV}-${AWS_REGION}-TestingExec" >> $GITHUB_ENV
      echo "TESTING_ARTIFACTS_BUCKET=thiscovery-devops-${AWS_TEST_ENV}-deployment-artifacts" >> $GITHUB_ENV
      echo "CLOUDFORMATION_EXECUTION_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-devops-${AWS_TEST_ENV}-${AWS_REGION}-CFExec" >> $GITHUB_ENV
      echo "DEPLOYMENT_METHOD=github_actions" >> $GITHUB_ENV
      echo "STAGING_DEPLOYMENT_ROLE=arn:aws:iam::${{ secrets.STAGING_AWS_ACCOUNT }}:role/thiscovery-devops-staging-${AWS_REGION}-PipelineExec" >> $GITHUB_ENV
      echo "PROD_DEPLOYMENT_ROLE=arn:aws:iam::${{ secrets.PROD_AWS_ACCOUNT }}:role/thiscovery-devops-prod-${AWS_REGION}-PipelineExec" >> $GITHUB_ENV
  
  - name: DEBUG STEP - check that test environment is set correctly
    run: |
      echo "Aws test account: ${AWS_TEST_ACCOUNT}"
      echo "Aws test env: ${AWS_TEST_ENV}"
      echo "Secrets namespace: ${SECRETS_NAMESPACE}"
      echo "Unit test namespace: ${UNIT_TEST_NAMESPACE}"
      echo "Testing account deployment role: ${TESTING_ACCOUNT_DEPLOYMENT_ROLE}"
      echo "Testing account test role: ${TESTING_ACCOUNT_TEST_ROLE}"
      echo "STAGING_DEPLOYMENT_ROLE: ${STAGING_DEPLOYMENT_ROLE}"
